# Generated by Django 6.0.2 on 2026-06-19 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Формат: +375XXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +375XXXXXXXXX (всего 12 символов, без пробелов).', regex='^\\+375\\d{9}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +375XXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +375XXXXXXXXX (всего 12 символов, без пробелов).', regex='^\\+375\\d{9}$')], verbose_name='Телефон'),
        ),
    ]
